Load balancer

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,30 +1,33 @@
 #!/usr/bin/env bash
-#srcipt that copies web server 1 to web server 2 for load balancing
-# Install Nginx
+# Customizing a 404 error page in Nginx
+
+set -e  # Exit immediately if a command exits with a non-zero status
+
+# Update Packages before performing installations
 sudo apt-get update
 sudo apt-get install -y nginx
 
-# Set variables
-nginx_conf="/etc/nginx/sites-available/default"
-hostname=$(hostname)
+# Create an index.html page
+echo "Hello World!" | sudo tee /var/www/html/index.html
 
-# Configure custom Nginx response header
-echo "server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
+# Perform a "moved permanently redirection" (301)
+nginx_config="/etc/nginx/sites-enabled/default"
+new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
+sudo sed -i "s/server_name _;/$new_string/" "$nginx_config"
 
-    server_name _;
+# Create a 404 Custom error page
+echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
+new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
+sudo sed -i "s/listen 80 default_server;/$new_string/" "$nginx_config"
 
-    add_header X-Served-By $hostname;
+# Create an HTTP response header
+new_header="add_header X-Served-By $HOSTNAME;"
+sudo sed -i "/server_name _/a $new_header" "$nginx_config"
 
-    location / {
-        root /var/www/html;
-        index index.html index.htm;
-    }
-}" | sudo tee "$nginx_conf" > /dev/null
+# Test configurations for syntax errors
+sudo nginx -t
 
-# Reload Nginx to apply changes
-sudo systemctl reload nginx
+# Restart nginx after implementing changes
+sudo systemctl restart nginx
 
-# Display success message
-echo "Nginx configured with custom header on $hostname"
+echo "Nginx configuration updated successfully!"
